apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-ping-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-ping
  template:
    metadata:
      labels:
        app: py-ping
    spec:
      containers:
        - name: py-ping
          image: m1kkou/py-ping:latest
