apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: py-ping-helm-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: py-ping-helm-svc
                port:
                  number: 2346
