apiVersion: v1
kind: Service
metadata:
  name: py-ping-helm-svc
spec:
  type: ClusterIP
  selector:
    app: py-ping-helm
  ports:
    - name: ping
      port: 2346
      protocol: TCP
      targetPort: 3000
